//local describe, test, expect = Test.describe, Test.it, Test.expect

local item = Item.New("stone", 1)
print(item)
local stack = TestReflect.GetField(item, "stack")
print(stack)
// print(stack.get("amount"))
// print(stack.amount)
local amount = TestReflect.CallMethod(stack, "getAmount")
print(amount)

//describe("example", function()
//    describe("module1", function()
//        test("feature1", function()
//            expect.equal('something', 'something')
//        end)
//        test("feature2", function()
//            expect.truthy(false)
//        end)
//    end)
//end)